dist: xenial
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
addons:
  rethinkdb: 2.3
install:
  - pip install .[dev]
# TODO: This is (hopefully) only temporary, until Travis fixes it
before_script: sudo service rethinkdb stop && sudo service rethinkdb start
script: pytest
deploy:
  provider: pypi
  user: linkyndy
  password:
    secure: "K7lrgkEOm9bDf7EEBQqGxDjnjAVBpQTOec9PmFgB/C8YWUJhhI8mhs/b6JCh32p9AQACbUn/2BBUVqWnTL0exBPQNsVzkpUeaj9OZJD8kFjx0uv5YwDzjEufh1dMJNUYzx2J3KGcDvn6aKSP0RXxLCFF97a6WYc9YN8tutlSLbQ="
  on:
    tags: true
  skip_existing: true
