language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
addons:
  - rethinkdb: 2.3
install:
  - pip install .
script: py.test tests/
deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    tags: true
